name: Kubernetes Role Change Guidance
description: Provide a comment explaining how safely to handle role additions / removals
branding:
  icon: alert-triangle
  color: blue
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  # Requires that the pull request's merge commit is checked out
  # to the current working directory.
  steps:
    - run: ${{ github.action_path }}/run.rb
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
