name: Test

on: push

jobs:
  test:
    name: rubocop and rspec
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: zendesk/setup-ruby@v1.192.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop && bundle exec rspec -f d
